version: '3.8'
services:
  sprint06_auth_pg:
    image: postgres:15.0-alpine
    volumes:
      - sprint06_auth_pg01data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 3s
      timeout: 20s
      retries: 5
      start_period: 80s

  sprint06_auth_api:
    build: ./auth_api
    env_file:
      - ./.env
    depends_on:
      sprint06_auth_pg:
        condition: service_healthy
    ports:
      - 8000:8000
    container_name: sprint06_auth_api

  sprint06_auth_redis:
    image: redis:latest
    volumes:
      - sprint06_auth_redis01data:/data

    command: >
      --save 60 1

volumes:
  sprint06_auth_pg01data:
  sprint06_auth_redis01data: