version: '3.8'
services:
  sprint06_auth_pg:
    image: postgres:15.0-alpine
    volumes:
      - sprint06_auth_pg01data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 3s
      timeout: 20s
      retries: 5
      start_period: 80s
    ports:
      - 5432:5432

  sprint06_auth_api:
    build: ./auth_api
    env_file:
      - ./.env
    depends_on:
      sprint06_auth_pg:
        condition: service_healthy
    volumes:
      - sprint06_auth_api_static:/usr/local/lib/python3.10/site-packages/flasgger/ui3/static/
      - ./auth_api:/auth_api:rw
    expose:
      - 8000
    tty: true
    container_name: sprint06_auth_api

  sprint06_auth_redis:
    image: redis:latest
    volumes:
      - sprint06_auth_redis01data:/data

    command: >
      --save 60 1

  nginx:
    image: nginx:1.23.3
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - sprint06_auth_api_static:/static:ro
    depends_on:
      - sprint06_auth_api
    ports:
      - 88:80
    container_name: nginx_auth

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - 6831:6831/udp
      - 16686:16686
    container_name: jaeger
  

volumes:
  sprint06_auth_pg01data:
  sprint06_auth_redis01data:
  sprint06_auth_api_static: