version: '3'
services:
  sprint06_auth_pg:
    image: postgres:15.0-alpine
    volumes:
      - sprint06_auth_pg01data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 3s
      timeout: 20s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"

  sprint06_auth_api:
    build: ./auth_api
    env_file:
      - ./.env
    # volumes:
    #   - ./auth_api:/auth_api:rw
    tty: true
    depends_on:
      sprint06_auth_pg:
        condition: service_healthy
    ports:
      - 8000:8000
    # command: bash -c "alembic upgrade head"
    
  sprint06_auth_pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./.env
    ports:
      - '5050:80'
    depends_on:
      - sprint06_auth_pg

  sprint06_auth_redis:
    image: redis:latest
    volumes:
      - sprint06_auth_redis01data:/data:rw

    command: >
      --save 60 1

volumes:
  sprint06_auth_pg01data:
  sprint06_auth_redis01data: