from api_conf import Settings


configs = Settings()

DB_ENGINE = configs.DATABASE.ENGINE
POSTGRES_DB = configs.POSTGRES.DB_NAME
POSTGRES_SCHEMA_NAME = configs.POSTGRES.SCHEMA_NAME
POSTGRES_PASSWORD = configs.POSTGRES.PASSWORD
POSTGRES_USER = configs.POSTGRES.USERNAME
POSTGRES_HOST = configs.POSTGRES.HOST
POSTGRES_PORT = configs.POSTGRES.PORT
POSTGRES_OPTIONS = configs.POSTGRES.OPTIONS
DB_URI = f"{DB_ENGINE}://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

REDIS_HOST = configs.REDIS.HOST
REDIS_EXPIRE = configs.REDIS.EXPIRE
REDIS_PORT = configs.REDIS.PORT

PGADMIN_DEFAULT_EMAIL = configs.PGADMIN.DEFAULT_EMAIL
PGADMIN_DEFAULT_PASSWORD = configs.PGADMIN.DEFAULT_PASSWORD
